package:
  format-version: "1.0.0"
  name: "smartenergy_g3"
  version: "v1.0.0"
  type: "api"
  status: "production"
  required: false

  dependencies:
    - name: "smartenergy"
      type: "package"
      version: "v1.2.0"
    - name: "core"
      type: "package"
      version: "v3.13.2"
    - name: "crypto"
      type: "package"
      version: "dev"
    - name: "wolfssl"
      type: "package"
      version: "v5.4.0"
    - name: "net"
      type: "package"
      version: "v3.11.0"
